name: Build

on:
  push:
    branches: [ "master", "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master", "main" ]
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-apworld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create minecraft.apworld
        run: |
          cd worlds
          zip -r ../minecraft_fabric.apworld minecraft_fabric

      - name: Upload APWorld Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Archipelago-Worlds
          path: "*.apworld"

      - name: Update Release with APWorlds (tag push or published release)
        if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: "*.apworld"
          tag_name: ${{ github.event_name == 'release' && github.event.release.tag_name || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}